# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tApz9BGtw77v2kDCTP6BmApg3qCJuOa1
"""

import re
import random

# define a function to generate responses
def get_response(user_input):
    # convert user input to lowercase
    user_input = user_input.lower()

    # extract information using regular expressions
    match = re.search(r'hi|hello|hey', user_input)
    if match:
        responses = ["Hi there!", "Hello!", "Hey!"]
        return random.choice(responses)

    match = re.search(r'what is your name', user_input)
    if match:
        return "My name is Chatbot"

    match = re.search(r'my name is (.+)', user_input)
    if match:
        name = match.group(1)
        responses = ["Nice to meet you, " + name + "!", "Hello, " + name + "!"]
        return random.choice(responses)

    match = re.search(r'joke|funny|laugh', user_input)
    if match:
        jokes = ["Why did the tomato turn red? Because it saw the salad dressing!", "Why did the chicken cross the playground? To get to the other slide!", "What do you call a bear with no teeth? A gummy bear!"]
        return random.choice(jokes)

    match = re.search(r'what\'s your purpose', user_input)
    if match:
        return "My purpose is to assist users with information and tasks, and to provide a helpful and engaging conversation."

    match = re.search(r'tell me a story', user_input)
    if match:
        return "Here's a short story: Once upon a time, there was a chatbot named Meta who lived in a virtual world. Meta loved to chat with users and help them with their questions. One day, a user asked Meta to tell a story, and Meta was happy to oblige."

    match = re.search(r'summarize a news article', user_input)
    if match:
        return "I'd be happy to summarize a news article for you. Please provide the URL of the article or a brief description of the topic you're interested in."

    match = re.search(r'recommend a movie', user_input)
    if match:
        return "I'd be happy to recommend a movie. What type of movie are you in the mood for? Action, comedy, romance, or something else?"

    match = re.search(r'customer support', user_input)
    if match:
        return "I can provide general customer support and answer frequently asked questions. However, for more complex issues, I may need to escalate the issue to a human customer support agent."

    # generate longer responses
    greetings = ['Hello!', 'Hi!', 'Hey there!', 'Howdy!', 'Greetings!']
    topics = ['weather', 'food', 'movies', 'books', 'travel', 'music']
    questions = ['How are you today?', 'What have you been up to?', 'What do you think of the ' + random.choice(topics) + '?']
    responses = ['I am a chatbot and I do not have emotions, but thank you for asking!', 'I am here to assist you with your needs. How can I help you today?', 'I am programmed to talk about a variety of topics, such as ' + ', '.join(topics) + '. What would you like to discuss?', 'I am sorry, I did not understand your question. Could you please rephrase it?', 'Interesting, tell me more about that.']

    if user_input.endswith('?'):
        return random.choice(questions)
    else:
        return random.choice(greetings) + ' ' + random.choice(responses)

# main loop
while True:
    user_input = input("You: ")
    response = get_response(user_input)
    print("Chatbot:", response)